[package]
name = "victoria-dom"
version = "0.1.0"
authors = ["Aleksandr Orlenko <zxteam@gmail.com>"]
publish = false

[dependencies]
regex = "0.2"
lazy_static = "0.2"
uuid = { version = "0.4.0", features = ["v4"] }
maplit = "0.1"
